baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Irvine Coding Club'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: '&copy; <a class="zerostatic" href="https://irvinecoding.club">irvinecoding.club</a>'

seo:
  meta_og_title: Irvine Coding Club"
  meta_og_type: "website"
  meta_og_url: "https://irvinecoding.club"
  meta_og_image: ""
  meta_og_description: "Irvine Coding Club is an non profit orgnization for students who enjoy programming in Orange County."
  meta_twitter_card: "summary"
  meta_twitter_site: "@irvinecodingclub"
  meta_twitter_creator: "@irvinecodingclub"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
