header:
    title:
    text: 
    button: JOIN OUR DISCORD
    buttonlink: "#services"

services:
    title: "Services"
    section: services
    list:
      - title: "Webinar"
        desc: "Free webinars from experts in different aspects of information technoledgy."
        icon: fas fa-shopping-cart #find more at https://fontawesome.com/icons
      - title: "Programming Classes"
        desc: "Classes for learning Scratch, Python, Javascript, Java and more..."
        icon: fas fa-laptop
      - title: "Coding Competition"
        desc: "We regularly offer coding competition. "
        icon: fab fa-markdown

portfolio:
    title: "Classes"
    section: portfolio
    closebutton: "Close Project"


timeline:
    title: "About"
    text: "Lorem ipsum timeline"
    section: timeline
    # left is the default
    #start_align: "left"
    events:
      - title: "Our Humble Beginnings"
        year: "Jan 2021"
        desc: "Irvine coding club was created by a group of orange county students!"
        image: assets/img/timeline/1.jpg
        alt:
      - title: "We have our first webinar"
        year: "Jan 2021"
        desc: "We have our first webinar : what's the life of being a programmer? More than 20 students joined the first seminar."
        image: assets/img/timeline/2.jpg
        alt:
      - title: "More to come ..."
        year: "2021"
        desc: "Ravi Riley converted Agency, a Bootstrap-based theme, into a Jekyll theme. The Jekyll theme can be installed as a Ruby gem, or remotely. For more information, visit the documentation."
        image: assets/img/timeline/3.jpg
        alt: image alt text
        # you can enforce the aligment
        align: right
    end: "Be Part <br> of Our <br> Story!"

about:
    title: "About Us"
    text: "our story"
    section: about


team:
    title: "OUR AMAZING TEAM"
    section: team
    people:
      - name: "Coding Kitty"
        role: "Chief Tasting Officer"
        image: https://media.giphy.com/media/VbnUQpnihPSIgIXuZv/giphy.gif

      - name: "Crazy Bob"
        role: "Chief Hacking Officer"
        image: https://media4.giphy.com/media/p4NLw3I4U0idi/giphy.gif?cid=ecf05e47xwutivg9rdislciqohen4xyk1nfunne9k2lmgw2b&rid=giphy.gif

      - name: "Picachu"
        role: "Lead Developer"
        image: https://media1.giphy.com/media/SEocHdq1aEcU/giphy.gif?cid=ecf05e4771f965613d83a9dfdeccbb457262f97b16c7a2cc&rid=giphy.gif


footer:
    legal: "Privacy Policy"
    social:
      - url: https://twitter.com
        icon: "fab fa-twitter"
      - url: https://facebook.com
        icon: "fab fa-facebook-f"
      - url: https://instagram.com
        icon: "fab fa-instagram"


# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
